-- DDL -
CREATE → create database objects
ALTER → modify structure
DROP → delete objects
TRUNCATE → remove all records (faster than DELETE)
-- DML -
SELECT → retrieve data
INSERT → add new data
UPDATE → modify existing data
DELETE → remove data
-- DCL -
GRANT → give permissions
REVOKE → remove permissions
-- TCL - 
COMMIT → save changes
ROLLBACK → undo changes
SAVEPOINT → temporary checkpoint

-- Type of Keys
Primary
Foreign
Candidate
Alternate
Composite
Unique
Super
Natural
Surrogate -- Artifical Key generated by system like Auto_Increment

--
Functions in Sql - P(R) represents a pattern drawn by Julia in R rows. The following pattern represents P(5):

* 
* * 
* * * 
* * * * 
* * * * *

SET @TEMP:=0; 
SELECT REPEAT('* ', @TEMP:= @TEMP + 1) 
FROM INFORMATION_SCHEMA.TABLES
WHERE @TEMP < 20;

WITH RECURSIVE pattern AS ( SELECT 1 AS n UNION ALL SELECT n + 1 FROM pattern WHERE n < 20 ) SELECT REPEAT('* ', n) FROM pattern;

With p(n) as ( select 1 as n union all select n+1 from p where n<20 ) select replicate(' *',n) from p;
--

-- Hackerrank
-- Occupations
WITH numbered AS ( SELECT Name, Occupation, ROW_NUMBER() OVER (PARTITION BY Occupation ORDER BY Name) AS rn FROM Occupations) 
SELECT MAX(CASE WHEN Occupation = 'Doctor' THEN Name END) AS Doctor, MAX(CASE WHEN Occupation = 'Professor' THEN Name END) AS Professor, MAX(CASE WHEN Occupation = 'Singer' THEN Name END) AS Singer, MAX(CASE WHEN Occupation = 'Actor' THEN Name END) AS Actor FROM numbered GROUP BY rn ORDER BY rn;


-- BST
select distinct T1.N,
case
    when T1.P is NULL then "Root"
    when T1.N = T2.P then "Inner"
    else "Leaf"
end  
from BST as T1
left join BST as T2 ON T1.N=T2.P
order by T1.N;
