-- DDL -
CREATE → create database objects
ALTER → modify structure
DROP → delete objects
TRUNCATE → remove all records (faster than DELETE)
-- DML -
SELECT → retrieve data
INSERT → add new data
UPDATE → modify existing data
DELETE → remove data
-- DCL -
GRANT → give permissions
REVOKE → remove permissions
-- TCL - 
COMMIT → save changes
ROLLBACK → undo changes
SAVEPOINT → temporary checkpoint

-- Type of Keys
Primary
Foreign
Candidate
Alternate
Composite
Unique
Super
Natural
Surrogate -- Artifical Key generated by system like Auto_Increment

--
Functions in Sql - P(R) represents a pattern drawn by Julia in R rows. The following pattern represents P(5):

* 
* * 
* * * 
* * * * 
* * * * *

SET @TEMP:=0; 
SELECT REPEAT('* ', @TEMP:= @TEMP + 1) 
FROM INFORMATION_SCHEMA.TABLES
WHERE @TEMP < 20;

WITH RECURSIVE pattern AS ( SELECT 1 AS n UNION ALL SELECT n + 1 FROM pattern WHERE n < 20 ) SELECT REPEAT('* ', n) FROM pattern;

With p(n) as ( select 1 as n union all select n+1 from p where n<20 ) select replicate(' *',n) from p;
--
